//
// $Id$
//
// Copyright (c) 2017, Juniper Networks, Inc.
// All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.9.1
// source: jnx_base_types.proto

package common

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Global status codes to be returned in response messages.
// Per-RPC specific status/error codes are to be conveyed
// in sub-codes defined in respective API definitions.
type StatusCode int32

const (
	//* Indicates that the RPC executed without error
	StatusCode_SUCCESS StatusCode = 0
	//* Indicates a failure condition that should be treated as fatal
	StatusCode_FAILURE StatusCode = 1
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_jnx_base_types_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_jnx_base_types_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_jnx_base_types_proto_rawDescGZIP(), []int{0}
}

//*
// Message containing an associated key value
// pair
type StrKeyStrVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StrKeyStrVal) Reset() {
	*x = StrKeyStrVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jnx_base_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrKeyStrVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrKeyStrVal) ProtoMessage() {}

func (x *StrKeyStrVal) ProtoReflect() protoreflect.Message {
	mi := &file_jnx_base_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrKeyStrVal.ProtoReflect.Descriptor instead.
func (*StrKeyStrVal) Descriptor() ([]byte, []int) {
	return file_jnx_base_types_proto_rawDescGZIP(), []int{0}
}

func (x *StrKeyStrVal) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StrKeyStrVal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

//*
// Message representing timeval structure
type TimeVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds      uint64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Microseconds uint64 `protobuf:"varint,2,opt,name=microseconds,proto3" json:"microseconds,omitempty"`
}

func (x *TimeVal) Reset() {
	*x = TimeVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jnx_base_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimeVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeVal) ProtoMessage() {}

func (x *TimeVal) ProtoReflect() protoreflect.Message {
	mi := &file_jnx_base_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeVal.ProtoReflect.Descriptor instead.
func (*TimeVal) Descriptor() ([]byte, []int) {
	return file_jnx_base_types_proto_rawDescGZIP(), []int{1}
}

func (x *TimeVal) GetSeconds() uint64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *TimeVal) GetMicroseconds() uint64 {
	if x != nil {
		return x.Microseconds
	}
	return 0
}

//*
// RPC execution status information
type RpcStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//*
	// Numerical code indicating success or failure of an RPC
	Code StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=jnxBase.StatusCode" json:"code,omitempty"`
	//*
	// Informational message string usually used to convey reason for the
	// RPC failure
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RpcStatus) Reset() {
	*x = RpcStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jnx_base_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStatus) ProtoMessage() {}

func (x *RpcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_jnx_base_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStatus.ProtoReflect.Descriptor instead.
func (*RpcStatus) Descriptor() ([]byte, []int) {
	return file_jnx_base_types_proto_rawDescGZIP(), []int{2}
}

func (x *RpcStatus) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_SUCCESS
}

func (x *RpcStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var file_jnx_base_types_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "jnxBase.japi_version",
		Tag:           "bytes,50000,opt,name=japi_version",
		Filename:      "jnx_base_types.proto",
	},
}

// Extension fields to descriptor.FileOptions.
var (
	// optional string japi_version = 50000;
	E_JapiVersion = &file_jnx_base_types_proto_extTypes[0]
)

var File_jnx_base_types_proto protoreflect.FileDescriptor

var file_jnx_base_types_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6a, 0x6e, 0x78, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6a, 0x6e, 0x78, 0x42, 0x61, 0x73, 0x65, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x36, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x47, 0x0a, 0x07, 0x54, 0x69, 0x6d,
	0x65, 0x56, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x22, 0x4e, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x27, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x6a, 0x6e, 0x78, 0x42, 0x61, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0x26, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x3a, 0x41, 0x0a, 0x0c, 0x6a, 0x61,
	0x70, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x6a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x10, 0x5a,
	0x0e, 0x6a, 0x6e, 0x78, 0x2f, 0x6a, 0x65, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jnx_base_types_proto_rawDescOnce sync.Once
	file_jnx_base_types_proto_rawDescData = file_jnx_base_types_proto_rawDesc
)

func file_jnx_base_types_proto_rawDescGZIP() []byte {
	file_jnx_base_types_proto_rawDescOnce.Do(func() {
		file_jnx_base_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_jnx_base_types_proto_rawDescData)
	})
	return file_jnx_base_types_proto_rawDescData
}

var file_jnx_base_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jnx_base_types_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jnx_base_types_proto_goTypes = []interface{}{
	(StatusCode)(0),                // 0: jnxBase.StatusCode
	(*StrKeyStrVal)(nil),           // 1: jnxBase.StrKeyStrVal
	(*TimeVal)(nil),                // 2: jnxBase.TimeVal
	(*RpcStatus)(nil),              // 3: jnxBase.RpcStatus
	(*descriptor.FileOptions)(nil), // 4: google.protobuf.FileOptions
}
var file_jnx_base_types_proto_depIdxs = []int32{
	0, // 0: jnxBase.RpcStatus.code:type_name -> jnxBase.StatusCode
	4, // 1: jnxBase.japi_version:extendee -> google.protobuf.FileOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jnx_base_types_proto_init() }
func file_jnx_base_types_proto_init() {
	if File_jnx_base_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jnx_base_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrKeyStrVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jnx_base_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimeVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jnx_base_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jnx_base_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_jnx_base_types_proto_goTypes,
		DependencyIndexes: file_jnx_base_types_proto_depIdxs,
		EnumInfos:         file_jnx_base_types_proto_enumTypes,
		MessageInfos:      file_jnx_base_types_proto_msgTypes,
		ExtensionInfos:    file_jnx_base_types_proto_extTypes,
	}.Build()
	File_jnx_base_types_proto = out.File
	file_jnx_base_types_proto_rawDesc = nil
	file_jnx_base_types_proto_goTypes = nil
	file_jnx_base_types_proto_depIdxs = nil
}
