# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jnx_authentication_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import jnx_common_base_types_pb2 as jnx__common__base__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n jnx_authentication_service.proto\x12\x16jnx.jet.authentication\x1a\x1bjnx_common_base_types.proto\"W\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x10\n\x08group_id\x18\x04 \x01(\t\"J\n\rLoginResponse\x12)\n\x06status\x18\x01 \x01(\x0b\x32\x19.jnx.jet.common.RpcStatusJ\x04\x08\x02\x10\x03R\x08sub_code2h\n\x0e\x41uthentication\x12V\n\x05Login\x12$.jnx.jet.authentication.LoginRequest\x1a%.jnx.jet.authentication.LoginResponse\"\x00\x42\x11\x82\xb5\x18\x05\x30.1.0\x8a\xb5\x18\x04\x32\x31.4b\x06proto3')



_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINRESPONSE = DESCRIPTOR.message_types_by_name['LoginResponse']
LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'jnx_authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.authentication.LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'jnx_authentication_service_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.authentication.LoginResponse)
  })
_sym_db.RegisterMessage(LoginResponse)

_AUTHENTICATION = DESCRIPTOR.services_by_name['Authentication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\202\265\030\0050.1.0\212\265\030\00421.4'
  _LOGINREQUEST._serialized_start=89
  _LOGINREQUEST._serialized_end=176
  _LOGINRESPONSE._serialized_start=178
  _LOGINRESPONSE._serialized_end=252
  _AUTHENTICATION._serialized_start=254
  _AUTHENTICATION._serialized_end=358
# @@protoc_insertion_point(module_scope)
