# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jnx_common_base_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bjnx_common_base_types.proto\x12\x0ejnx.jet.common\x1a google/protobuf/descriptor.proto\"0\n\x07TimeVal\x12\x0f\n\x07seconds\x18\x01 \x01(\x04\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x04\"F\n\tRpcStatus\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.jnx.jet.common.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x0cNumericRange\x12\x0b\n\x03min\x18\x01 \x01(\r\x12\x0b\n\x03max\x18\x02 \x01(\r\"D\n\x10NumericRangeList\x12\x30\n\nrange_list\x18\x01 \x03(\x0b\x32\x1c.jnx.jet.common.NumericRange*&\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01:4\n\x0cjapi_version\x12\x1c.google.protobuf.FileOptions\x18\xd0\x86\x03 \x01(\t:5\n\rjunos_release\x12\x1c.google.protobuf.FileOptions\x18\xd1\x86\x03 \x01(\tB\x11\x82\xb5\x18\x05\x30.1.0\x8a\xb5\x18\x04\x31\x38.4b\x06proto3')

_STATUSCODE = DESCRIPTOR.enum_types_by_name['StatusCode']
StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
SUCCESS = 0
FAILURE = 1

JAPI_VERSION_FIELD_NUMBER = 50000
japi_version = DESCRIPTOR.extensions_by_name['japi_version']
JUNOS_RELEASE_FIELD_NUMBER = 50001
junos_release = DESCRIPTOR.extensions_by_name['junos_release']

_TIMEVAL = DESCRIPTOR.message_types_by_name['TimeVal']
_RPCSTATUS = DESCRIPTOR.message_types_by_name['RpcStatus']
_NUMERICRANGE = DESCRIPTOR.message_types_by_name['NumericRange']
_NUMERICRANGELIST = DESCRIPTOR.message_types_by_name['NumericRangeList']
TimeVal = _reflection.GeneratedProtocolMessageType('TimeVal', (_message.Message,), {
  'DESCRIPTOR' : _TIMEVAL,
  '__module__' : 'jnx_common_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.common.TimeVal)
  })
_sym_db.RegisterMessage(TimeVal)

RpcStatus = _reflection.GeneratedProtocolMessageType('RpcStatus', (_message.Message,), {
  'DESCRIPTOR' : _RPCSTATUS,
  '__module__' : 'jnx_common_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.common.RpcStatus)
  })
_sym_db.RegisterMessage(RpcStatus)

NumericRange = _reflection.GeneratedProtocolMessageType('NumericRange', (_message.Message,), {
  'DESCRIPTOR' : _NUMERICRANGE,
  '__module__' : 'jnx_common_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.common.NumericRange)
  })
_sym_db.RegisterMessage(NumericRange)

NumericRangeList = _reflection.GeneratedProtocolMessageType('NumericRangeList', (_message.Message,), {
  'DESCRIPTOR' : _NUMERICRANGELIST,
  '__module__' : 'jnx_common_base_types_pb2'
  # @@protoc_insertion_point(class_scope:jnx.jet.common.NumericRangeList)
  })
_sym_db.RegisterMessage(NumericRangeList)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(japi_version)
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(junos_release)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\202\265\030\0050.1.0\212\265\030\00418.4'
  _STATUSCODE._serialized_start=315
  _STATUSCODE._serialized_end=353
  _TIMEVAL._serialized_start=81
  _TIMEVAL._serialized_end=129
  _RPCSTATUS._serialized_start=131
  _RPCSTATUS._serialized_end=201
  _NUMERICRANGE._serialized_start=203
  _NUMERICRANGE._serialized_end=243
  _NUMERICRANGELIST._serialized_start=245
  _NUMERICRANGELIST._serialized_end=313
# @@protoc_insertion_point(module_scope)
